DROP STREAM IF EXISTS POSTS_META_STREAM; \
CREATE STREAM POSTS_META_STREAM \
WITH (kafka_topic='mysql-server.wordpress.wp_postmeta', value_format='AVRO');


DROP STREAM IF EXISTS POSTS_META_TOPIC; \
CREATE STREAM POSTS_META_TOPIC \
AS SELECT * FROM POSTS_META_STREAM PARTITION BY meta_id;


DROP TABLE IF EXISTS POSTS_META_TABLE; \
CREATE TABLE POSTS_META_TABLE \
(KEY VARCHAR PRIMARY KEY) \
WITH (KAFKA_TOPIC='mysql-server.wordpress.wp_postmeta', VALUE_FORMAT='AVRO');


CREATE TABLE CUSTOMERS (CUSTOMER_ID VARCHAR PRIMARY KEY)
  WITH (KAFKA_TOPIC='asgard.demo.CUSTOMERS', VALUE_FORMAT='AVRO');


SET 'auto.offset.reset' = 'earliest';

SELECT * FROM POSTS_META_TABLE EMIT CHANGES;

SELECT * FROM POSTS_META_STREAM EMIT CHANGES;


DROP TABLE IF EXISTS POSTS_META_TABLE;

CREATE TABLE POSTS_META_TABLE AS \
SELECT meta_id, LATEST_BY_OFFSET(post_id) AS post_id, 
       LATEST_BY_OFFSET(meta_key) AS meta_key, 
       LATEST_BY_OFFSET(meta_value) AS meta_value 
FROM POSTS_META_STREAM 
GROUP BY meta_id;


DROP TABLE IF EXISTS POSTS_META_TABLE;
CREATE TABLE POSTS_META_TABLE 
(meta_id INT PRIMARY KEY, post_id INT, meta_key VARCHAR, meta_value VARCHAR) 
WITH (KAFKA_TOPIC='mysql-server.wordpress.wp_postmeta', VALUE_FORMAT='JSON');