version: '2'
services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    volumes:
      - 'mysql_data:/bitnami/mysql'
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_magento
      - MYSQL_DATABASE=bitnami_magento
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"
  magento:
    image: docker.io/bitnami/magento:2
    privileged: true
    ports:
      - "8080:8080"
      - '8443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mysql
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      # confs são padrões para o mariadb
      # - MAGENTO_DATABASE_USER=bn_magento
      # - MAGENTO_DATABASE_NAME=bitnami_magento
      # observar que no mysql são diferentes
      # https://hub.docker.com/r/bitnami/magento
      #- MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_ADMIN_URL_PREFIX=admin
      - MAGENTO_EXTERNAL_HTTP_PORT_NUMBER=8080
      #- MAGENTO_USERNAME: Magento application username. Default: user
      #- MAGENTO_PASSWORD: Magento application password. Default: bitnami1
      # - MAGENTO_USE_SECURE=1
      # - MAGENTO_BASE_URL_SECURE=1
      # - MAGENTO_USE_SECURE_ADMIN=1
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mysql
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  kib03:
    image: docker.elastic.co/kibana/kibana:7.17.10
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

volumes:
  mysql_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
